### ISSUE TITLE
Enrollment failed with error in amazon managed blockchain

### ISSUE THREAD

**Issue by jitrani** [aws-samples/non-profit-blockchain#38]
In part-3(run the restful api server):
while enroll a user that time i am getting error:{"success":false,"message":"failed Error: Enrollment failed with errors [[{\"code\":20,\"message\":\"Authorization failure\"}]]".

**Comment by MCLDG** [comment]
Similar to the other issue, I suspect this is because the admin username or password in config.json is incorrect.

**Comment by victorbrast** [comment]
@MCLDG  got the same issue. 

The credentials work fine using the fabric-cli in a container running inside a ec2 instance. But whenever I set the credentials in the config.json and also in the connection profile .yaml got a similar behavior. In the logs it says the enrollment is working but the registration of the user fails with this error: "**Invalid token in authorization header: Token signature validation failed**" is some kind of contradiction since the user admin is already logged in and the admin enrollment was successful. This is the log from the CA logs when trying to register a user:


[DEBUG] Received registration request from : { Name:usr_nodejs Type: Secret:**** MaxEnrollments:1 Affiliation: Attributes:[] CAName:m-UM62OLNY3FGDHOUTLJQN3XBQWW }
[INFO] 10.0.3.151:23167 POST /api/v1/**register 401 25 "Invalid token in authorization header: Token signature validation failed"**
[DEBUG] Received request for /api/v1/register
[INFO] Successfully exported Admin Cert
[INFO] 10.0.4.204:29083 **POST /api/v1/enroll 201 0 "OK"**
[DEBUG] Successfully incremented state for identity admin to 22
[DEBUG] Checking to see if caller 'admin' has the hf.Admin attribute
[DEBUG] Certificate enrolled for Fabric Admin: admin
[DEBUG] Attempting to export Admin Cert
[INFO] Adding admin cert to external store for user: admin

Also tried with other users that were created from the ec2 instance running fabric client.
